<?php

return [
    'admin_path' => env('ADMIN_PATH', 'studio-panel'),
    'microsaas_public_path' => env('MICROSAAS_PUBLIC_PATH', 'microsaas'),
    'ad_placeholder' => env('SEO_PLACEHOLDER_AD_CODE', '<div data-ad-slot="article-inline"></div>'),
    'vertex' => [
        'api_key' => env('VERTEX_API_KEY'),
        'project_id' => env('VERTEX_PROJECT_ID'),
        'location' => env('VERTEX_LOCATION', 'global'),
        'publisher' => env('VERTEX_PUBLISHER', 'google'),
        'model' => env('VERTEX_MODEL', 'gemini-2.5-flash-lite'),
        'articles_per_run' => (int) env('VERTEX_ARTICLES_PER_RUN', 5),
        'max_output_tokens' => (int) env('VERTEX_MAX_OUTPUT_TOKENS', 1300),
        'temperature' => (float) env('VERTEX_TEMPERATURE', 0.35),
        'top_p' => (float) env('VERTEX_TOP_P', 0.85),
    ],
    'seo' => [
        'dispatch_times' => array_values(array_filter(array_map(
            static fn (string $time): string => trim($time),
            explode(',', env('SEO_DISPATCH_TIMES', '00:30,02:30,04:30,06:30,08:30,10:30,12:30,14:30,16:30,20:30'))
        ))),
        'dispatch_limit_per_run' => env('SEO_DISPATCH_LIMIT_PER_RUN') !== null
            ? (int) env('SEO_DISPATCH_LIMIT_PER_RUN')
            : null,
        'daily_min_articles' => (int) env('SEO_DAILY_MIN_ARTICLES', 5),
        'daily_max_articles' => (int) env('SEO_DAILY_MAX_ARTICLES', 7),
        'article_min_words' => (int) env('SEO_ARTICLE_MIN_WORDS', 450),
        'article_max_words' => (int) env('SEO_ARTICLE_MAX_WORDS', 650),
        'allowed_categories' => [
            'urban_farming',
            'informatics_learning',
            'business_growth',
        ],
        'default_language' => env('SEO_DEFAULT_LANGUAGE', 'id'),
        'default_country_code' => env('SEO_DEFAULT_COUNTRY_CODE', 'ID'),
        'themes' => [
            'urban_farming' => [
                'label' => 'Hidroponik, Tanaman, dan Menanam',
                'description' => 'Edukasi tanam praktis, hidroponik rumahan, perawatan tanaman, dan panduan berkebun yang mudah diterapkan.',
                'search_intents' => ['informational', 'commercial'],
                'keyword_pool' => [
                    'cara menanam selada hidroponik untuk pemula',
                    'nutrisi hidroponik sayuran daun yang bagus',
                    'cara merawat tanaman cabai di pot',
                    'media tanam terbaik untuk sayuran rumahan',
                    'langkah menanam tomat dari biji di rumah',
                    'cara membuat kebun mini di lahan sempit',
                    'jadwal penyiraman tanaman sayur yang benar',
                    'tips menanam pakcoy hidroponik cepat panen',
                    'cara mengatasi daun tanaman menguning',
                    'tanaman herbal yang mudah ditanam di rumah',
                    'cara menanam kangkung hidroponik anti gagal',
                    'peralatan hidroponik sederhana untuk rumah',
                ],
                'content_focus' => 'Bahas budidaya, perawatan, alat, dan solusi masalah umum seputar hidroponik, tanaman hias, tanaman konsumsi, dan kegiatan menanam di rumah.',
            ],
            'informatics_learning' => [
                'label' => 'Pelajaran Informatika',
                'description' => 'Materi belajar informatika yang rapi untuk pelajar, mahasiswa, dan pemula yang ingin paham konsep sampai praktik.',
                'search_intents' => ['informational', 'commercial'],
                'keyword_pool' => [
                    'penjelasan algoritma untuk siswa pemula',
                    'belajar basis data dari nol untuk pelajar',
                    'contoh flowchart sederhana dan cara membacanya',
                    'materi logika informatika yang mudah dipahami',
                    'perbedaan frontend dan backend untuk pemula',
                    'cara belajar coding pertama kali secara terarah',
                    'materi sistem operasi untuk siswa informatika',
                    'contoh project informatika sederhana untuk sekolah',
                    'pengertian jaringan komputer dan fungsi dasarnya',
                    'belajar HTML CSS untuk tugas sekolah',
                    'cara memahami pseudocode dengan cepat',
                    'materi keamanan data untuk pelajar informatika',
                ],
                'content_focus' => 'Fokus pada penjelasan konsep informatika, materi sekolah atau kuliah, latihan dasar, dan panduan belajar bertahap yang tidak terlalu teknis di awal.',
            ],
            'business_growth' => [
                'label' => 'Bisnis',
                'description' => 'Topik bisnis praktis untuk usaha kecil, digital product, pemasaran, operasional, dan pengembangan bisnis.',
                'search_intents' => ['informational', 'commercial', 'transactional'],
                'keyword_pool' => [
                    'cara memulai bisnis kecil dari rumah',
                    'strategi pemasaran digital untuk UMKM',
                    'cara menentukan harga jual produk yang sehat',
                    'ide bisnis modal kecil yang realistis',
                    'cara membuat rencana bisnis sederhana',
                    'tips meningkatkan repeat order pelanggan',
                    'cara riset pasar untuk bisnis pemula',
                    'sistem operasional sederhana untuk usaha kecil',
                    'cara membuat branding bisnis lebih meyakinkan',
                    'strategi promosi bisnis tanpa buang budget',
                    'cara mengelola cash flow usaha kecil',
                    'contoh funnel penjualan untuk produk digital',
                ],
                'content_focus' => 'Bahas strategi bisnis, marketing, penjualan, operasional, produktivitas usaha, dan pengembangan bisnis yang aplikatif untuk pemula sampai menengah.',
            ],
        ],
    ],
];
