<?php

return [
    'branding' => [
        'logo_url' => env('PORTAL_LOGO_URL'),
        'logo_alt' => env('PORTAL_LOGO_ALT', env('PORTAL_SITE_NAME', env('APP_NAME', 'Arena Nalar'))),
        'mark_text' => env('PORTAL_MARK_TEXT', 'AN'),
    ],
    'admin_path' => env('ADMIN_PATH', 'studio-panel'),
    'microsaas_public_path' => env('MICROSAAS_PUBLIC_PATH', 'microsaas'),
    'ad_placeholder' => env('SEO_PLACEHOLDER_AD_CODE', '<div data-ad-slot="article-inline"></div>'),
    'vertex' => [
        'api_key' => env('VERTEX_API_KEY'),
        'project_id' => env('VERTEX_PROJECT_ID'),
        'location' => env('VERTEX_LOCATION', 'global'),
        'publisher' => env('VERTEX_PUBLISHER', 'google'),
        'model' => env('VERTEX_MODEL', 'gemini-2.5-pro'),
        'articles_per_run' => (int) env('VERTEX_ARTICLES_PER_RUN', 12),
        'max_output_tokens' => (int) env('VERTEX_MAX_OUTPUT_TOKENS', 2100),
        'temperature' => (float) env('VERTEX_TEMPERATURE', 0.28),
        'top_p' => (float) env('VERTEX_TOP_P', 0.9),
    ],
    'seo' => [
        'dispatch_times' => array_values(array_filter(array_map(
            static fn (string $time): string => trim($time),
            explode(',', env('SEO_DISPATCH_TIMES', '00:15,02:15,04:15,06:15,08:15,10:15,12:15,14:15,16:15,18:15,20:15,22:15'))
        ))),
        'dispatch_limit_per_run' => env('SEO_DISPATCH_LIMIT_PER_RUN') !== null
            ? (int) env('SEO_DISPATCH_LIMIT_PER_RUN')
            : null,
        'daily_min_articles' => (int) env('SEO_DAILY_MIN_ARTICLES', 12),
        'daily_max_articles' => (int) env('SEO_DAILY_MAX_ARTICLES', 18),
        'article_min_words' => (int) env('SEO_ARTICLE_MIN_WORDS', 700),
        'article_max_words' => (int) env('SEO_ARTICLE_MAX_WORDS', 1200),
        'article_images' => [
            'enabled' => env('SEO_ARTICLE_IMAGES_ENABLED', '1') === '1',
            'max_per_article' => (int) env('SEO_ARTICLE_IMAGES_MAX', 1),
            'directories' => [
                'sports_training' => array_values(array_filter([
                    env('SEO_ARTICLE_IMAGES_DIR_SPORTS_TRAINING'),
                    'article-images/sports-training',
                ])),
                'sports_places' => array_values(array_filter([
                    env('SEO_ARTICLE_IMAGES_DIR_SPORTS_PLACES'),
                    'article-images/sports-places',
                ])),
                'sports_gear' => array_values(array_filter([
                    env('SEO_ARTICLE_IMAGES_DIR_SPORTS_GEAR'),
                    'article-images/sports-gear',
                ])),
                'it_insights' => array_values(array_filter([
                    env('SEO_ARTICLE_IMAGES_DIR_IT_INSIGHTS'),
                    'article-images/it-insights',
                ])),
                'hydroponics' => array_values(array_filter([
                    env('SEO_ARTICLE_IMAGES_DIR_HYDROPONICS'),
                    'article-images/hydroponics',
                ])),
            ],
        ],
        'allowed_categories' => [
            'sports_training',
            'sports_places',
            'sports_gear',
            'it_insights',
            'hydroponics',
        ],
        'default_language' => env('SEO_DEFAULT_LANGUAGE', 'id'),
        'default_country_code' => env('SEO_DEFAULT_COUNTRY_CODE', 'ID'),
        'themes' => [
            'sports_training' => [
                'label' => 'Teknik dan Latihan Olahraga',
                'description' => 'Bahas teknik dasar, pola latihan, recovery, dan peningkatan performa untuk olahraga yang sedang ramai dicari.',
                'search_intents' => ['informational'],
                'keyword_pool' => [
                    'teknik footwork badminton untuk pemula',
                    'cara latihan passing futsal yang benar',
                    'teknik dasar lari sprint untuk pemula',
                    'latihan kekuatan untuk pemain voli amatir',
                    'cara meningkatkan stamina untuk sepak bola',
                    'teknik servis tenis meja yang konsisten',
                    'drill basket untuk memperbaiki shooting',
                    'cara recovery otot setelah latihan intens',
                    'latihan mobilitas untuk pemain padel',
                    'teknik renang gaya bebas untuk pemula',
                    'cara pemanasan sebelum main badminton',
                    'latihan core untuk performa olahraga',
                ],
                'content_focus' => 'Fokus pada teknik olahraga, jadwal latihan, pencegahan cedera, recovery, dan tips performa yang relevan untuk pembaca umum.',
            ],
            'sports_places' => [
                'label' => 'Tempat dan Olahraga Terdekat',
                'description' => 'Panduan memilih tempat olahraga, venue terdekat, kelas latihan, dan fasilitas yang cocok untuk kebutuhan pembaca.',
                'search_intents' => ['informational'],
                'keyword_pool' => [
                    'cara mencari lapangan badminton terdekat yang bagus',
                    'tips memilih gym terdekat untuk pemula',
                    'cara memilih kelas padel terdekat',
                    'faktor penting saat memilih kolam renang umum',
                    'panduan memilih tempat futsal indoor',
                    'cara menilai fasilitas jogging track kota',
                    'tips memilih studio pilates terdekat',
                    'cara memilih tempat yoga untuk pemula',
                    'rekomendasi kriteria lapangan basket sewa',
                    'cara membandingkan membership gym harian',
                    'tips memilih tempat olahraga keluarga',
                    'panduan cek fasilitas olahraga komunitas',
                ],
                'content_focus' => 'Bahas cara memilih venue olahraga, kelas, dan fasilitas terdekat tanpa mengarang alamat spesifik yang tidak terverifikasi.',
            ],
            'sports_gear' => [
                'label' => 'Perlengkapan dan Rekomendasi Olahraga',
                'description' => 'Rekomendasi raket, sepatu, bola, pakaian, dan aksesori olahraga dengan angle pemilihan yang membantu pembaca.',
                'search_intents' => ['informational'],
                'keyword_pool' => [
                    'cara memilih raket badminton untuk intermediate',
                    'sepatu lari harian yang nyaman untuk pemula',
                    'perbedaan bola futsal dan bola sepak',
                    'cara memilih grip raket yang tepat',
                    'rekomendasi matras yoga untuk rumah',
                    'cara memilih smartwatch untuk olahraga',
                    'rompi lari dan hydration pack yang praktis',
                    'cara memilih sepatu basket untuk outdoor',
                    'rekomendasi resistance band untuk latihan rumah',
                    'cara memilih helm sepeda untuk commuting',
                    'tips membeli jersey olahraga yang adem',
                    'raket tenis meja untuk pemula yang stabil',
                ],
                'content_focus' => 'Fokus pada buying guide, perbandingan fitur, kecocokan pemakaian, dan catatan beli yang jujur untuk perlengkapan olahraga.',
            ],
            'it_insights' => [
                'label' => 'IT, Tutorial, dan Perkembangan Teknologi',
                'description' => 'Campuran materi IT yang bisa dipelajari ulang, insight tools, perkembangan teknologi, dan penjelasan yang mudah dicopas sebagai catatan belajar.',
                'search_intents' => ['informational'],
                'keyword_pool' => [
                    'perbedaan cloud server dan shared hosting',
                    'cara belajar git untuk pemula',
                    'tren ai untuk developer tahun ini',
                    'cara deploy laravel ke vps dengan aman',
                    'belajar api dan webhook dari nol',
                    'perbandingan typescript dan javascript untuk pemula',
                    'cara memilih laptop coding sesuai kebutuhan',
                    'penjelasan docker sederhana untuk developer',
                    'cara kerja ci cd untuk project kecil',
                    'trend cyber security yang perlu dipahami',
                    'cara membuat dokumentasi teknis yang rapi',
                    'roadmap backend developer pemula',
                ],
                'content_focus' => 'Bahas tutorial IT, praktik deploy, tools developer, tren teknologi, dan materi belajar yang padat serta mudah dipakai ulang.',
            ],
            'hydroponics' => [
                'label' => 'Hidroponik dan Urban Farming',
                'description' => 'Topik hidroponik tetap dipertahankan untuk pembaca yang mencari panduan tanam praktis, nutrisi, dan perawatan.',
                'search_intents' => ['informational'],
                'keyword_pool' => [
                    'cara menanam selada hidroponik untuk pemula',
                    'nutrisi hidroponik sayuran daun yang bagus',
                    'cara merawat tanaman cabai di pot',
                    'media tanam terbaik untuk sayuran rumahan',
                    'langkah menanam tomat dari biji di rumah',
                    'cara membuat kebun mini di lahan sempit',
                    'jadwal penyiraman tanaman sayur yang benar',
                    'tips menanam pakcoy hidroponik cepat panen',
                    'cara mengatasi daun tanaman menguning',
                    'tanaman herbal yang mudah ditanam di rumah',
                    'cara menanam kangkung hidroponik anti gagal',
                    'peralatan hidroponik sederhana untuk rumah',
                ],
                'content_focus' => 'Bahas budidaya, nutrisi, alat, perawatan, dan solusi masalah umum seputar hidroponik dan urban farming.',
            ],
        ],
    ],
];
